---
version: '3.1'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - db-path:/var/lib/postgres/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: helloworld
      POSTGRES_PASSWORD: example
      POSTGRES_DB: laboredattack

  adminer:
    image: adminer
    restart: always
    links:
      - "db:postgres"
    ports:
      - 8080:8080
volumes:
  db-path:
